MESSAGE_UUID = "messageUuid"
CREATED_DATE_UTC = "messageCreateDateUtc"
LIMS_ID = "limsId"
ALIQUOT_ID = "aliquotId"
ALIQUOT_TYPE = "aliquotType"
SOURCE_TYPE = "sourceType"
SOURCE_BARCODE = "sourceBarcode"
SAMPLE_NAME = "sampleName"
USED_BY_TYPE = "usedByType"
USED_BY_BARCODE = "usedByBarcode"
CONCENTRATION = "concentration"
VOLUME = "volume"
INSERT_SIZE = "insertSize"
RECORDED_AT = "recordedAt"

TRACTION_LIMS = "Traction"
