MESSAGE_UUID = "messageUuid"
CREATED_DATE_UTC = "messageCreateDateUtc"
LABWARE = "labware"
LABWARE_TYPE = "labwareType"
BARCODE = "barcode"
SAMPLES = "samples"
UUID = "labwareUuid"


SAMPLE_PUBLIC_NAME = "publicName"
SAMPLE_COMMON_NAME = "commonName"
SAMPLE_CONCENTRATION = "concentration"
SAMPLE_COUNTRY_OF_ORIGIN = "countryOfOrigin"
SAMPLE_DONOR_ID = "donorId"
SAMPLE_LABWARE_TYPE = "labwareType"
SAMPLE_LIBRARY_TYPE = "libraryType"
SAMPLE_LOCATION = "location"
SAMPLE_SANGER_SAMPLE_ID = "sangerSampleId"
SAMPLE_SANGER_TAXON_ID = "taxonId"
SAMPLE_SANGER_UUID = "sampleUuid"
SAMPLE_STUDY_UUID = "studyUuid"
SAMPLE_COLLECTION_DATE = "sampleCollectionDateUtc"
SAMPLE_VOLUME = "volume"
SAMPLE_ACCESSION_NUMBER = "accessionNumber"
SAMPLE_GENOME_SIZE = "genomeSize"
SAMPLE_COST_CODE = "costCode"
