MESSAGE_UUID = "messageUuid"
CREATED_DATE_UTC = "messageCreateDateUtc"
LABWARE = "labware"
LABWARE_TYPE = "labwareType"
BARCODE = "barcode"
SAMPLES = "samples"
UUID = "labwareUuid"


SAMPLE_PUBLIC_NAME = "publicName"
SAMPLE_COMMON_NAME = "commonName"
SAMPLE_CONCENTRATION = "concentration"
SAMPLE_COUNTRY_OF_ORIGIN = "countryOfOrigin"
SAMPLE_DONOR_ID = "donorId"
SAMPLE_LABWARE_TYPE = "labwareType"
SAMPLE_LIBRARY_TYPE = "libraryType"
SAMPLE_LOCATION = "location"
SAMPLE_SANGER_SAMPLE_ID = "sangerSampleId"
SAMPLE_SANGER_TAXON_ID = "taxonId"
SAMPLE_SANGER_UUID = "sampleUuid"
SAMPLE_STUDY_UUID = "studyUuid"
SAMPLE_COLLECTION_DATE = "sampleCollectionDateUtc"
SAMPLE_VOLUME = "volume"
SAMPLE_ACCESSION_NUMBER = "accessionNumber"
SAMPLE_GENOME_SIZE = "genomeSize"
SAMPLE_COST_CODE = "costCode"

SHEARED_FEMTO_FRAGMENT_SIZE = "shearedFemtoFragmentSize"
POST_SPRI_CONCENTRATION = "postSPRIConcentration"
POST_SPRI_VOLUME = "postSPRIVolume"
FINAL_NANODROP_280 = "finalNanoDrop280"
FINAL_NANODROP_230 = "finalNanoDrop230"
FINAL_NANODROP = "finalNanoDrop"
SHEARING_QC_COMMENTS = "shearingAndQCComments"
DATE_SUBMITTED_UTC = "dateSubmittedUTC"
PRIORITY_LEVEL = "priorityLevel"
DATE_REQUIRED_BY = "dateRequiredBy"
REASON_FOR_PRIORITY = "reasonForPriority"