RABBITMQ_SUBJECT_CREATE_LABWARE = "create-labware"
RABBITMQ_SUBJECT_UPDATE_LABWARE = "update-labware"
RABBITMQ_FEEDBACK_EXCHANGE = "psd.tol"
RABBITMQ_ROUTING_KEY_CREATE_LABWARE_FEEDBACK = "feedback.created.labware"
RABBITMQ_ROUTING_KEY_UPDATE_LABWARE_FEEDBACK = "feedback.updated.labware"
RABBITMQ_SUBJECT_CREATE_LABWARE_FEEDBACK = "create-labware-feedback"
RABBITMQ_SUBJECT_UPDATE_LABWARE_FEEDBACK = "update-labware-feedback"

